[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-local-cluster"
description = "Blockchain, Rebuilt for Scale"
version = "1.0.17"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
itertools = "0.8.1"
log = "0.4.8"
rand = "0.6.5"
solana-archiver-lib = { path = "../archiver-lib", version = "1.0.17" }
solana-config-program = { path = "../programs/config", version = "1.0.17" }
solana-core = { path = "../core", version = "1.0.17" }
solana-client = { path = "../client", version = "1.0.17" }
solana-faucet = { path = "../faucet", version = "1.0.17" }
solana-exchange-program = { path = "../programs/exchange", version = "1.0.17" }
solana-genesis-programs = { path = "../genesis-programs", version = "1.0.17" }
solana-ledger = { path = "../ledger", version = "1.0.17" }
solana-logger = { path = "../logger", version = "1.0.17" }
solana-runtime = { path = "../runtime", version = "1.0.17" }
solana-sdk = { path = "../sdk", version = "1.0.17" }
solana-stake-program = { path = "../programs/stake", version = "1.0.17" }
solana-storage-program = { path = "../programs/storage", version = "1.0.17" }
solana-vest-program = { path = "../programs/vest", version = "1.0.17" }
solana-vote-program = { path = "../programs/vote", version = "1.0.17" }
tempfile = "3.1.0"
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "1.0.17" }

[dev-dependencies]
assert_matches = "1.3.0"
serial_test = "0.3.2"
serial_test_derive = "0.4.0"
