[package]
name = "solana-archiver-lib"
version = "1.1.5"
description = "Solana Archiver Library"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
bincode = "1.2.1"
crossbeam-channel = "0.4"
ed25519-dalek = "=1.0.0-pre.1"
log = "0.4.8"
rand = "0.6.5"
rand_chacha = "0.1.1"
solana-client = { path = "../client", version = "1.1.5" }
solana-storage-program = { path = "../programs/storage", version = "1.1.5" }
thiserror = "1.0"
serde = "1.0.105"
serde_json = "1.0.48"
serde_derive = "1.0.103"
solana-net-utils = { path = "../net-utils", version = "1.1.5" }
solana-chacha = { path = "../chacha", version = "1.1.5" }
solana-chacha-sys = { path = "../chacha-sys", version = "1.1.5" }
solana-ledger = { path = "../ledger", version = "1.1.5" }
solana-logger = { path = "../logger", version = "1.1.5" }
solana-perf = { path = "../perf", version = "1.1.5" }
solana-sdk = { path = "../sdk", version = "1.1.5" }
solana-core = { path = "../core", version = "1.1.5" }
solana-streamer = { path = "../streamer", version = "1.1.5" }
solana-archiver-utils = { path = "../archiver-utils", version = "1.1.5" }
solana-metrics = { path = "../metrics", version = "1.1.5" }

[dev-dependencies]
hex = "0.4.2"

[lib]
name = "solana_archiver_lib"
