[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-validator"
description = "Blockchain, Rebuilt for Scale"
version = "1.1.3"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
clap = "2.33.0"
chrono = { version = "0.4.11", features = ["serde"] }
console = "0.10.0"
log = "0.4.8"
rand = "0.6.5"
serde_json = "1.0.48"
solana-clap-utils = { path = "../clap-utils", version = "1.1.3" }
solana-client = { path = "../client", version = "1.1.3" }
solana-core = { path = "../core", version = "1.1.3" }
solana-download-utils = { path = "../download-utils", version = "1.1.3" }
solana-faucet = { path = "../faucet", version = "1.1.3" }
solana-ledger = { path = "../ledger", version = "1.1.3" }
solana-logger = { path = "../logger", version = "1.1.3" }
solana-perf = { path = "../perf", version = "1.1.3" }
solana-metrics = { path = "../metrics", version = "1.1.3" }
solana-net-utils = { path = "../net-utils", version = "1.1.3" }
solana-runtime = { path = "../runtime", version = "1.1.3" }
solana-sdk = { path = "../sdk", version = "1.1.3" }
solana-vote-program = { path = "../programs/vote", version = "1.1.3" }
solana-vote-signer = { path = "../vote-signer", version = "1.1.3" }

[target."cfg(unix)".dependencies]
gag = "0.1.10"
