[package]
name = "solana-chacha-cuda"
version = "1.0.18"
description = "Solana Chacha Cuda APIs"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
log = "0.4.8"
solana-archiver-utils = { path = "../archiver-utils", version = "1.0.18" }
solana-chacha = { path = "../chacha", version = "1.0.18" }
solana-ledger = { path = "../ledger", version = "1.0.18" }
solana-logger = { path = "../logger", version = "1.0.18" }
solana-perf = { path = "../perf", version = "1.0.18" }
solana-sdk = { path = "../sdk", version = "1.0.18" }

[dev-dependencies]
hex-literal = "0.2.1"

[lib]
name = "solana_chacha_cuda"
