[package]
name = "solana-merkle-tree"
version = "1.0.21"
description = "Solana Merkle Tree"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
solana-sdk = { path = "../sdk", version = "1.0.21" }

[dev-dependencies]
hex = "0.4.0"

[lib]
crate-type = ["lib"]
name = "solana_merkle_tree"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
