[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-archiver"
version = "0.23.8"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
clap = "2.33.0"
console = "0.9.1"
solana-clap-utils = { path = "../clap-utils", version = "0.23.8" }
solana-core = { path = "../core", version = "0.23.8" }
solana-logger = { path = "../logger", version = "0.23.8" }
solana-metrics = { path = "../metrics", version = "0.23.8" }
solana-archiver-lib = { path = "../archiver-lib", version = "0.23.8" }
solana-net-utils = { path = "../net-utils", version = "0.23.8" }
solana-sdk = { path = "../sdk", version = "0.23.8" }

