[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-bench-streamer"
version = "1.1.4"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
clap = "2.33.0"
solana-clap-utils = { path = "../clap-utils", version = "1.1.4" }
solana-streamer = { path = "../streamer", version = "1.1.4" }
solana-logger = { path = "../logger", version = "1.1.4" }
solana-net-utils = { path = "../net-utils", version = "1.1.4" }
